// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleBookCatalog.Infrastructure.Context;

#nullable disable

namespace SimpleBookCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(SimpleBookCatalogDbContext))]
    partial class SimpleBookCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SimpleBookCatalog.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jane Appleton",
                            Category = 1,
                            PublicationDate = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Science of Everything"
                        },
                        new
                        {
                            Id = 2,
                            Author = "John Fit",
                            Category = 3,
                            PublicationDate = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Modern Fitness Guide"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Sara Tech",
                            Category = 2,
                            PublicationDate = new DateTime(2021, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tech Innovations"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Marco Polo",
                            Category = 4,
                            PublicationDate = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "World Travel Atlas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
